F #3951: Document fireedge setup
OpenNebula/docs pull request #1413
Opened 2021-01-21 11:26 UTC by sbbarragan

2021-01-21 18:20 UTC, tinova requested changes

2021-01-21 18:20 UTC, tinova commented on source/configuration_guide/fireedge_configuration/fireedge_sunstone.rst
> +To configure the Fireedge server on Sunstone where they are **on different servers**, you will need
there are two endpoints, public and private, please specify

2021-01-22 08:37 UTC, sbbarragan commented on source/configuration_guide/fireedge_configuration/fireedge_cpi.rst
> +Fireedge OneProvision is build using `oneprovision` tool which allows the deployment of OpenNebia clusters
_OpenNebia clusters_  ----> **OpenNebula clusters**

2021-01-22 08:37 UTC, sbbarragan commented on source/configuration_guide/fireedge_configuration/fireedge_install.rst
> +- **Start OneProvision GUI**, to ease the the deployment of fully operational OpenNebula
double _the_

2021-01-22 09:29 UTC, tinova approved these changes

2021-01-22 09:29 UTC, merged