M #: Improve VM backups docs
OpenNebula/docs pull request #1944
Opened 2021-08-30 11:31 UTC by christian7007

2021-08-30 16:58 UTC, al3xhh requested changes

2021-08-30 16:58 UTC, al3xhh commented on source/management_and_operations/vm_management/vm_backup.rst
> +    $
This extra $ should be removed.

2021-09-06 17:17 UTC, tinova approved these changes

2021-09-06 17:17 UTC, tinova commented
will do some changes after merge

2021-09-06 17:18 UTC, merged