F#6430 Replaced Sunstone w/FireEdge images in Backup …
OpenNebula/docs pull request #2906
Opened 2024-05-07 08:27 UTC by pedroielpi3

…Guide

### Description

### Branches to which this PR applies

- [x] master
- [ ] one-X.X
- [ ] one-X.X-maintenance

<hr>

- [ ] Check this if this PR should **not** be squashed

2024-05-07 08:32 UTC, tinova requested changes

2024-05-07 08:32 UTC, tinova commented on source/images/backup_schedule.png
i'd rather use the resulting dialog after pressing add action, it's more telling than just an empty sched actions subtab

2024-05-07 09:27 UTC, pedroielpi3 commented on source/images/backup_schedule.png
Indeed that's more informative. My only doubt is that some readers may not understand how to reach the "Schedule action" dialog box, since the image would not show the "Add Action" button which produces that dialog. If needed I can make a slight modification in the doc text to reflect this, or create a composite image that includes a mouse pointer on the "Add Action" button and the resulting dialog box. For now I've only added the image with the dialog box.

2024-05-07 11:04 UTC, tinova commented on source/images/backup_schedule.png
i see, i think modifying the text to reflect the need to press that Add Action is the most elegant way to solve this

2024-05-07 12:52 UTC, pedroielpi3 commented on source/images/backup_schedule.png
Yep, agreed. Modified the doc. For the button descriptions I used the same letter case as in the FireEdge UI (that's why it says "Add action" instead of "Add Action")

2024-05-07 14:32 UTC, tinova approved these changes

2024-05-08 09:35 UTC, tinova approved these changes

2024-05-08 09:35 UTC, tinova approved these changes

2024-05-08 09:35 UTC, tinova approved these changes

2024-05-08 09:36 UTC, merged