F OpenNebula/one#6430: Refactor services section
OpenNebula/docs pull request #2960
Opened 2024-07-04 12:59 UTC by vichansson

### Description

* Replace all sunstone ref's with ruby_sunstone

Refactored:
* Overview
* OpenNebula Configuration
* Scheduler Configuration
* Monitoring Configuration
* FireEdge Configuration
* Ruby Sunstone Configuration
* OneFlow Configuration
* OneGate Configuration
* Database Maintenance
* Troubleshooting
* Replace failing frontend
* Support Utilities (EE)

### Branches to which this PR applies

- [ ] master

<hr>

- [ ] Check this if this PR should **not** be squashed

2024-07-04 13:37 UTC, tinova requested changes

2024-07-04 13:37 UTC, tinova commented on source/installation_and_configuration/authentication/overview.rst
> +- :ref:`Sunstone Authentication <ruby_sunstone>`
i think is better to remove all Ruby Sunstone references. We'll move the standalone guides to Legacy section, and remove all references to Ruby Sunstone in the main doc

2024-07-05 09:39 UTC, vichansson commented on source/installation_and_configuration/opennebula_services/fireedge.rst
The `Configure Sunstone for VMRC and Guacamole` part is already present in the legacy documentation for sunstone service configuration

2024-07-05 11:06 UTC, tinova approved these changes

2024-07-05 11:06 UTC, merged